version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./src/:/app

  web:
    image: nginx:1.20-alpine
    ports:
      - 8081:80
    depends_on:
      - app
    volumes:
      - ./src/:/app
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf

  db:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./docker/db/my.conf:/etc/my.conf
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mysql-volume:
